default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: mumbi
  password: postgres
  host: localhost

development:
  <<: *default
  database: ticketwiz_development

test:
  <<: *default
  database: ticketwiz_test

production:
  <<: *default
  database: ticketwiz_production
  username: mumbi
  password: postgres
