MPESA_CONSUMER_KEY: 'LLFWMCiS8ZkCmSuy98cwGA5pLccse3uA'
MPESA_CONSUMER_SECRET: 'aiSrhAOigvxAhR2R'
MPESA_PASSKEY: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_SHORTCODE: '174379'
MPESA_INITIATOR_NAME: 'testapi'
MPESA_INITIATOR_PASSWORD: 'Safaricom999!*!'
CALLBACK_URL: 'https://1d27-102-219-210-70.ngrok-free.app'
REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"